name: Feature request
description: Proposer une amélioration
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problème / motivation
    validations:
      required: true
  - type: textarea
    attributes:
      label: Solution proposée
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considérées
    validations:
      required: false
